### ISSUE TITLE
Ordered arguments

### ISSUE THREAD

**Issue by vmstarchenko** [shmuelamar/cbox#1]
The idea of this project is really cool. However, it would be nice to add ability to use ordered arguments in terminal.

Implementation might be different.

 For example we could use decorators to define command declaration:
```python
@ordered_args('a', 'b')
def cmd(a: int, b: str='\n', c: int=0):
    ...
```

Or some special values:
```python
def cmd(a: int=Ordered(), b: str = Ordered('\n'), c: int = Named(0)):
    ...
```

Or something else

**Comment by vmstarchenko** [comment]
Additionally I think this tool will be more useful if there is a more flexible control of input arguments.

My suggestions:
- add ability to use shortcuts for arguments names (`-f filename` instead of `--filename FILENAME`)
- use shortcuts (`-f, --filename FILENAME`)
- describe  default values in help menu
- can use flags without values (`-d` without any value, `-d D` used now).

**Comment by shmuelamar** [comment]
Hi and thanks for opening this issue!

can you provide usage example? do you mean by _ordered arguments_ positional arguments like in [`argparse`](https://docs.python.org/2/library/argparse.html#default)?

**Comment by vmstarchenko** [comment]
Yes. I mean _positional arguments_.

For example, I want to pass one positional argument _filename_ to program:
```bash
echo "Hello world" | python write_to_file.py output.txt
```

But now I have to do it by keyword argument
```bash
echo "Hello world" | python write_to_file.py -filename output.txt
```

**Comment by shmuelamar** [comment]
sounds great, I assume to support more advanced per param config the best pattern would be:

```python
from cbox import Arg, cli

@cli
def foo(x: int=0, y: Arg(positional=True, pos=1)=5):
    pass
```

later we can make `Arg` with more options.
probably `pos=1` implies `positional=True` so one can do `Arg(pos=1)`.

is that sounds ok? do you want to implement it and submit a PR 😃

**Comment by vmstarchenko** [comment]
Yes. That sounds really good. 

About implementation. Well, I can do it but only next week.

**Comment by shmuelamar** [comment]
ok feel free to submit PR :) no need to rush

**Comment by shmuelamar** [comment]
I'm closing this issue for now, feel free to reopen it or push something to the PR.
Thanks again
