### ISSUE TITLE
Does cbox support subcommand?

### ISSUE THREAD

**Issue by cupen** [shmuelamar/cbox#3]
How about this style?
```python
@cbox.cmd
def web(listen :str, debug=False):
    """Description of web

    :param listen:  listen a address.(e.g.: 127.0.0.1:5000)
    :param debug:  yeah, debug it.
    """
    pass

@cbox.cmd
def export(db_url :str, debug=False):
    """Description of export

    :param listen:  database address.(e.g.: mysql://127.0.0.1:3306/dbname?user=hello&passwd=world)
    """
    pass

if __name__ == '__main__':
    cbox.main([web, export])
    pass
```

```
$ thispyscript --help
Usage:  thispyscript [OPTIONS] [COMMAND] [ARGS]

Options:
  -h, --help         show this help message and exit
  --debug            yeah, debug it.

Commands:
  web                Description of web
  export             Description of export
```

```
$ thispyscript web --help
Usage: thispyscript  [-h] --listen LISTEN [--debug DEBUG]

Description of web

Optional Arguments:
  -h, --help         show this help message and exit
  --listen           listen a address.(e.g.: 127.0.0.1:5000)
  --debug            yeah, debug it.
```
The `Options` will be some common paramters, the intersection of  all the `Command` parameters.

**Comment by shmuelamar** [comment]
hey @cupen thanks for opening this issue!
looks like great addition to cbox.
can you try make a PR? if not ill try do this at my free time which is a bit limited now.

**Comment by cupen** [comment]
@shmuelamar OK, I will try to commit a PR to you.

**Comment by shmuelamar** [comment]
thanks @cupen for the PR. merged and close.
if you are interested I'm considering adding AUTHORS.md file, would you like me to add your `@`name there? (similar to this https://github.com/requests/requests/blob/master/AUTHORS.rst)

**Comment by cupen** [comment]
@shmuelamar It's my pleasure.  I don't mind whether there is a `AUTHORS.md` file or not, but if you add it,  I am glad my name is there.
btw: the alias of my name is 王百万, it's a chinese funny name which means "a super rich man". 

haha, `王百万 <xcupen@gmail.com>`
